/* AUTO-GENERATED by scripts/update_xauusd.py. Do not hand-edit. */
window.XAUUSD_DATA = {
  "meta": {
    "pipelineVersion": "2.0.0",
    "generatedAt": "2026-09-17T09:22:02+08:00",
    "timezone": "Asia/Kuala_Lumpur",
    "cadence": "daily",
    "expectedUpdateLocal": "07:10",
    "staleAfterHours": 30,
    "verified": true,
    "seed": false,
    "sourceStatus": {
      "xau": {
        "ok": true,
        "label": "Twelve Data XAU/USD",
        "detail": "latest daily bar 2026-09-17",
        "timestamp": "2026-09-17T09:22:03+08:00"
      },
      "dxy": {
        "ok": false,
        "label": "Twelve Data DXY",
        "detail": "No exact/confirmed DXY symbol found",
        "timestamp": "2026-09-17T09:22:03+08:00"
      },
      "brent": {
        "ok": false,
        "label": "Twelve Data Brent",
        "detail": "404 Client Error: Not Found for url: https://api.twelvedata.com/time_series?symbol=XBR%2FUSD&interval=1day&outputsize=3&order=DESC&timezone=UTC&apikey=[REDACTED]",
        "timestamp": "2026-09-17T09:22:11+08:00"
      },
      "us10y": {
        "ok": true,
        "label": "FRED DGS10",
        "detail": "latest 2026-09-15",
        "timestamp": "2026-09-17T09:22:12+08:00"
      },
      "news": {
        "ok": true,
        "label": "NewsAPI",
        "detail": "8 recent items",
        "timestamp": "2026-09-17T09:22:12+08:00"
      },
      "fedSpeeches": {
        "ok": true,
        "label": "Federal Reserve speeches",
        "detail": "6 official listings",
        "timestamp": "2026-09-17T09:22:12+08:00"
      }
    },
    "warnings": [
      "DXY unavailable; dashboard shows — rather than substituting an unverified dollar index.",
      "Brent unavailable for this run."
    ]
  },
  "updated": "2026-09-17 09:22 MYT",
  "session": "Daily verified snapshot · sourced data + labelled heuristic overlays",
  "price": {
    "spot": 4305.74,
    "change": 41.68,
    "changePct": 0.98,
    "dayRange": "4,256.66 - 4,309.42",
    "monthPct": -6.43,
    "yearPct": -0.22,
    "ath": 5597.23,
    "note": "Latest provider daily bar: 2026-09-17; rolling history used: 370 bars"
  },
  "macro": [
    {
      "label": "DXY",
      "value": "—",
      "delta": "unavailable",
      "tone": "",
      "note": "Provider symbol not confirmed"
    },
    {
      "label": "US 10Y",
      "value": "5.000%",
      "delta": "+3.0 bp",
      "tone": "bad",
      "note": "FRED DGS10 · 2026-09-15"
    },
    {
      "label": "Brent",
      "value": "—",
      "delta": "unavailable",
      "tone": "",
      "note": "Provider symbol not confirmed"
    }
  ],
  "sentiment": {
    "bias": "MIXED",
    "goldTone": "NEUTRAL",
    "score": -0.086,
    "confidence": 69,
    "summary": "Mechanical daily pressure model using sourced USD/yield moves plus a small observed XAU-momentum term. It is not a forecast or trade instruction.",
    "netSpeechSignal": "NEUTRAL",
    "netSpeechPct": 0.0,
    "netNote": "Direction only. No fabricated percentage impact is assigned to headlines or speeches."
  },
  "model": {
    "base": 0.0,
    "formula": "dailyPressure = weighted(ΔDXY, ΔUS10Y, observed ΔXAU)",
    "note": "Transparent heuristic over sourced daily data. No headline/speech percentage impact is fabricated.",
    "weights": [
      {
        "k": "DXY daily move",
        "v": 0.45
      },
      {
        "k": "US 10Y daily move",
        "v": 0.45
      },
      {
        "k": "Observed XAU momentum",
        "v": 0.1
      }
    ],
    "strength": [
      {
        "k": "Source available",
        "v": 1.0
      },
      {
        "k": "Source unavailable",
        "v": 0.0
      }
    ],
    "surprise": [
      {
        "k": "Not auto-estimated",
        "v": 0.0
      }
    ]
  },
  "news": [
    {
      "time": "2026-09-16 01:00 UTC",
      "title": "Is an affordable style “winter” coming?",
      "summary": "Is the era of finding affordable, good looking clothes, shoes and watches coming to an end?",
      "source": "Dappered.com",
      "url": "https://dappered.com/2026/09/is-an-affordable-style-winter-coming/",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-16 01:00 UTC",
      "title": "Wo Long 2: Wings of Ember Hides New Mechanics Under Layers of Familiarity (Preview)",
      "summary": "Image Courtesy of Koei Tecmo\n\nTeam Ninja can’t stop or won’t stop — it’s not clear — but, regardless of the impetus, the result is an onslaught of Soulslikes. With each new release and the expansions that trickle out in the follwow, something from this side o…",
      "source": "ComicBook.com",
      "url": "http://comicbook.com/gaming/feature/wo-long-2-wings-of-ember-hides-new-mechanics-under-layers-of-familiarity-preview/",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-16 00:55 UTC",
      "title": "Turkish habit of stashing gold \"under the pillow' hurts economy, government says",
      "summary": "For years, Turks have stashed their gold at home against a raining day, mistrustful of banks. Now the government says that tradition hurts the economy",
      "source": "NPR",
      "url": "https://www.npr.org/2026/09/15/g-s1-143414/turkey-gold-economy",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-16 00:46 UTC",
      "title": "Treasury Rethinks AML Rules for Banks That Know Their Customers",
      "summary": "Treasury may raise longstanding bank reporting thresholds and take into account how long financial institutions have known their customers, Treasury Secretary Scott Bessent told lawmakers Tuesday (Sept. 15). House Financial Services Committee Chairman French …",
      "source": "pymnts.com",
      "url": "https://www.pymnts.com/legal/bank-regulation/2026/treasury-rethinks-aml-rules-for-banks-that-know-their-customers/",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-16 00:45 UTC",
      "title": "Hundreds of tons of gold moved from NY Fed to Bank of England amid China buying spree",
      "summary": "The gold transfer may signal shifting economic power dynamics, influencing global market stability and central bank strategies.\nThe post Hundreds of tons of gold moved from NY Fed to Bank of England amid China buying spree appeared first on Crypto Briefing.",
      "source": "Crypto Briefing",
      "url": "https://cryptobriefing.com/hundreds-of-tons-of-gold-moved-from-ny-fed-to-bank-of-england-amid-china-buying/",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-16 00:00 UTC",
      "title": "Gold Steadies Below $4,300 as Markets Await Fed Rate Decision",
      "summary": "Gold was steady as high oil prices continued to fuel inflation concerns and keep interest-rate hike bets a near-certainty ahead of the Federal Reserve's poli...",
      "source": "Yahoo Entertainment",
      "url": "https://finance.yahoo.com/markets/commodities/articles/gold-steadies-below-4-300-000015450.html",
      "impact": "bearish",
      "signal": "DOWN",
      "impactPct": null
    },
    {
      "time": "2026-09-16 00:00 UTC",
      "title": "Nvidia RTX 5090 GPU prices skyrocket to $9,000 — as fresh RTX 6000 rumor suggests a 2027 launch that fills me with dread",
      "summary": "The RTX 5090 keeps getting pricier somehow, so who knows how much the next-gen flagship will cost.",
      "source": "TechRadar",
      "url": "https://www.techradar.com/computing/gpu/nvidia-rtx-5090-gpu-prices-skyrocket-to-usd9-000-as-fresh-rtx-6000-rumor-suggests-a-2027-launch-that-fills-me-with-dread",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-16 00:00 UTC",
      "title": "Reimagining research papers as interactive and reliable AI agents",
      "summary": "Paper2Agent converts research papers into interactive artificial intelligence agents by turning manuscripts, code and data into model context protocol-based tool-invoking systems that reproduce original results, answer new scientific queries and collaborate t…",
      "source": "Nature.com",
      "url": "https://www.nature.com/articles/s41586-026-11044-y",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    }
  ],
  "speakers": [
    {
      "name": "The Economic Outlook and Some Comments on My Policy Communication",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "The Economic Outlook and Some Comments on My Policy Communication Watch Live Governor Christopher J. Waller At Reuters NEXT Newsmaker Interview, Washington, D.C.",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/waller20260903a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Unlocking Opportunities for Workers and Entrepreneurs with a Criminal Record",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Unlocking Opportunities for Workers and Entrepreneurs with a Criminal Record Watch Live Governor Michael S. Barr At the Second-Chance Lending Forum, Developing Evidence-Based Policy on Creditworthiness and Criminal History, Washington, D.C.",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/barr20260901a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "In Our Time",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "In Our Time Watch Live Chairman Kevin Warsh At âFinancial Innovation: Implications for Payments and Policy,â an economic policy symposium sponsored by the Federal Reserve Bank of Kansas City, Jackson Hole, Wyoming",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/warsh20260828a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Outlook for the U.S. and Alaskan Economies",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Outlook for the U.S. and Alaskan Economies Governor Lisa D. Cook At the 2026 Economic Luncheon of the Anchorage Economic Development Corporation, Anchorage, Alaska",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/cook20260805a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Navigating Economic Shocks: A Monetary Policymakerâs Perspective",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Navigating Economic Shocks: A Monetary Policymakerâs Perspective Watch Live Vice Chair Philip N. Jefferson At the Stanford Institute for Economic Policy Research, Stanford University, Stanford, California",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/jefferson20260716a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Economic Outlook",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Economic Outlook Governor Lisa D. Cook At The Exchequer Club of Washington D.C., Washington, D.C.",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/cook20260715a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    }
  ],
  "levels": {
    "resistance": [
      4336.31,
      4408.55,
      4457.52,
      4514.11
    ],
    "support": [
      4238.37,
      4215.1,
      4166.12,
      4093.88
    ],
    "note": "Classic pivot levels from previous daily OHLC plus recent 20-day extreme; mechanical, not guarantees."
  },
  "calendar": [],
  "pressure": [
    {
      "label": "US 10Y daily move",
      "level": "+3.0 bp",
      "w": 25,
      "dir": "down"
    },
    {
      "label": "Observed XAU momentum",
      "level": "+0.98%",
      "w": 65,
      "dir": "up"
    }
  ],
  "priceSeries": {
    "label": "XAU/USD daily close (Twelve Data)",
    "unit": "USD / troy oz",
    "yMin": 4244.15,
    "yMax": 4449.98,
    "points": [
      {
        "x": "2026-09-04",
        "y": 4430.06
      },
      {
        "x": "2026-09-05",
        "y": 4429.03
      },
      {
        "x": "2026-09-06",
        "y": 4429.01
      },
      {
        "x": "2026-09-07",
        "y": 4405.18
      },
      {
        "x": "2026-09-08",
        "y": 4356.03
      },
      {
        "x": "2026-09-09",
        "y": 4401.7
      },
      {
        "x": "2026-09-10",
        "y": 4316.76
      },
      {
        "x": "2026-09-11",
        "y": 4348.87
      },
      {
        "x": "2026-09-12",
        "y": 4348.46
      },
      {
        "x": "2026-09-13",
        "y": 4348.46
      },
      {
        "x": "2026-09-14",
        "y": 4298.35
      },
      {
        "x": "2026-09-15",
        "y": 4293.8
      },
      {
        "x": "2026-09-16",
        "y": 4264.07
      },
      {
        "x": "2026-09-17",
        "y": 4305.74
      }
    ]
  },
  "macroSeries": {
    "label": "DXY unavailable",
    "unit": "index",
    "yMin": 0,
    "yMax": 1,
    "points": [
      {
        "x": "2026-09-17",
        "y": 0
      }
    ]
  },
  "oddsSeries": {
    "label": "DXY unavailable",
    "unit": "index",
    "yMin": 0,
    "yMax": 1,
    "points": [
      {
        "x": "2026-09-17",
        "y": 0
      }
    ]
  },
  "sources": [
    "Twelve Data — XAU/USD daily market data",
    "Federal Reserve — official speech listings",
    "FRED — DGS10 US 10-Year Treasury Constant Maturity Rate",
    "NewsAPI — recent gold/macro headlines"
  ]
};
