/* AUTO-GENERATED by scripts/update_xauusd.py. Do not hand-edit. */
window.XAUUSD_DATA = {
  "meta": {
    "pipelineVersion": "2.0.0",
    "generatedAt": "2026-09-16T11:45:02+08:00",
    "timezone": "Asia/Kuala_Lumpur",
    "cadence": "daily",
    "expectedUpdateLocal": "07:10",
    "staleAfterHours": 30,
    "verified": true,
    "seed": false,
    "sourceStatus": {
      "xau": {
        "ok": true,
        "label": "Twelve Data XAU/USD",
        "detail": "latest daily bar 2026-09-16",
        "timestamp": "2026-09-16T11:45:03+08:00"
      },
      "dxy": {
        "ok": false,
        "label": "Twelve Data DXY",
        "detail": "No exact/confirmed DXY symbol found",
        "timestamp": "2026-09-16T11:45:03+08:00"
      },
      "brent": {
        "ok": false,
        "label": "Twelve Data Brent",
        "detail": "404 Client Error: Not Found for url: https://api.twelvedata.com/time_series?symbol=XBR%2FUSD&interval=1day&outputsize=3&order=DESC&timezone=UTC&apikey=6c8d081decdb4af99bf262642bcbabcb",
        "timestamp": "2026-09-16T11:45:11+08:00"
      },
      "us10y": {
        "ok": true,
        "label": "FRED DGS10",
        "detail": "latest 2026-09-14",
        "timestamp": "2026-09-16T11:45:11+08:00"
      },
      "news": {
        "ok": true,
        "label": "NewsAPI",
        "detail": "8 recent items",
        "timestamp": "2026-09-16T11:45:11+08:00"
      },
      "fedSpeeches": {
        "ok": true,
        "label": "Federal Reserve speeches",
        "detail": "6 official listings",
        "timestamp": "2026-09-16T11:45:11+08:00"
      }
    },
    "warnings": [
      "DXY unavailable; dashboard shows — rather than substituting an unverified dollar index.",
      "Brent unavailable for this run."
    ]
  },
  "updated": "2026-09-16 11:45 MYT",
  "session": "Daily verified snapshot · sourced data + labelled heuristic overlays",
  "price": {
    "spot": 4327.04,
    "change": 33.25,
    "changePct": 0.77,
    "dayRange": "4,275.88 - 4,339.71",
    "monthPct": -5.82,
    "yearPct": 0.28,
    "ath": 5597.23,
    "note": "Latest provider daily bar: 2026-09-16; rolling history used: 370 bars"
  },
  "macro": [
    {
      "label": "DXY",
      "value": "—",
      "delta": "unavailable",
      "tone": "",
      "note": "Provider symbol not confirmed"
    },
    {
      "label": "US 10Y",
      "value": "4.970%",
      "delta": "+1.0 bp",
      "tone": "bad",
      "note": "FRED DGS10 · 2026-09-14"
    },
    {
      "label": "Brent",
      "value": "—",
      "delta": "unavailable",
      "tone": "",
      "note": "Provider symbol not confirmed"
    }
  ],
  "sentiment": {
    "bias": "MIXED",
    "goldTone": "NEUTRAL",
    "score": 0.026,
    "confidence": 69,
    "summary": "Mechanical daily pressure model using sourced USD/yield moves plus a small observed XAU-momentum term. It is not a forecast or trade instruction.",
    "netSpeechSignal": "NEUTRAL",
    "netSpeechPct": 0.0,
    "netNote": "Direction only. No fabricated percentage impact is assigned to headlines or speeches."
  },
  "model": {
    "base": 0.0,
    "formula": "dailyPressure = weighted(ΔDXY, ΔUS10Y, observed ΔXAU)",
    "note": "Transparent heuristic over sourced daily data. No headline/speech percentage impact is fabricated.",
    "weights": [
      {
        "k": "DXY daily move",
        "v": 0.45
      },
      {
        "k": "US 10Y daily move",
        "v": 0.45
      },
      {
        "k": "Observed XAU momentum",
        "v": 0.1
      }
    ],
    "strength": [
      {
        "k": "Source available",
        "v": 1.0
      },
      {
        "k": "Source unavailable",
        "v": 0.0
      }
    ],
    "surprise": [
      {
        "k": "Not auto-estimated",
        "v": 0.0
      }
    ]
  },
  "news": [
    {
      "time": "2026-09-15 03:39 UTC",
      "title": "Emmys 2026 review: ‘Widow’s Bay’ sweeps an uneven night with over-the-top host Mariska Hargitay",
      "summary": "\"Widow's Bay\" swept, \"The Pitt\" won big, but not as big as expected, and Mariska Hargitay was an over-the-top host of the 2026 Emmys.",
      "source": "Page Six",
      "url": "https://pagesix.com/2026/09/14/entertainment/emmys-2026-review-widows-bay-sweeps-an-uneven-night-with-over-the-top-host-mariska-hargitay/",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-15 03:00 UTC",
      "title": "48 Legal Excuses So Ridiculous Even Lawyers Could Barely Believe Them",
      "summary": "Being a lawyer can be incredibly stressful. Going before a judge and defending important clients comes with a lot of pressure. But sometimes, the hardest part is just keeping your client from saying something stupid. Lawyers have been recalling the most absur…",
      "source": "Boredpanda.com",
      "url": "https://www.boredpanda.com/most-absurd-legal-justifications/",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-15 03:00 UTC",
      "title": "China buying twice more gold than officially reported amid surge in central bank purchases",
      "summary": "China's undisclosed gold purchases may signal a strategic reserve shift, potentially impacting global gold prices and market dynamics.\nThe post China buying twice more gold than officially reported amid surge in central bank purchases appeared first on Crypto…",
      "source": "Crypto Briefing",
      "url": "https://cryptobriefing.com/china-buying-twice-more-gold-than-officially-reported-amid-surge-in-central/",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-15 02:57 UTC",
      "title": "Asian shares slip as oil and yields rise ahead of Fed, BOJ meetings",
      "summary": "Asian equities struggled as investors assessed rising oil prices, West Asia tensions and concerns over AI development ahead of key US and Japan central bank meetings",
      "source": "Business Standard",
      "url": "https://www.business-standard.com/markets/news/asian-shares-slip-as-oil-and-yields-rise-ahead-of-fed-boj-meetings-126091500073_1.html",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-15 02:53 UTC",
      "title": "Oil and Treasury yields haven’t moved this closely in seven years. That’s bad news for markets",
      "summary": "Oil and 10-year Treasury yields are moving in near lockstep, with their correlation at its strongest since 2019.",
      "source": "CNBC",
      "url": "https://www.cnbc.com/2026/09/15/oil-us-treasurys-stocks-pressure.html",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-15 02:43 UTC",
      "title": "Asian shares waver as oil and yields rise ahead of Fed, BOJ meetings",
      "summary": "TOKYO: Asian shares struggled on Tuesday (Sep 15) as investors weighed Middle East tensions and calls by industry figures for a",
      "source": "CNA",
      "url": "https://www.channelnewsasia.com/business/asian-shares-kospi-bank-japan-6384761",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-15 02:26 UTC",
      "title": "Stock Market LIVE: GIFT Nifty signals positive open; Asian markets fall as firm oil prices weigh",
      "summary": "Sensex Today | Stock Market LIVE Updates Tuesday: The GIFT Nifty indicated a positive open for the Nifty50 index, while its Asian peers logged losses in inflation concerns",
      "source": "Business Standard",
      "url": "https://www.business-standard.com/markets/news/stock-market-live-september-15-nse-bse-sensex-today-nifty-gift-nifty-crude-oil-price-today-pranav-construction-ipo-listing-126091500075_1.html",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    },
    {
      "time": "2026-09-15 02:15 UTC",
      "title": "Economic Digest: A Snapshot of Nepal’s Business News",
      "summary": "KATHMANDU: Economic Digest presents a brief yet comprehensive roundup of major business developments in Nepal, delivered in clear and accessible summaries. Nepal’s economic landscape on Monday reflected a mix of market optimism, external pressures and the mou…",
      "source": "Khabarhub.com",
      "url": "https://english.khabarhub.com/2026/15/567808/",
      "impact": "neutral",
      "signal": "NEUTRAL",
      "impactPct": null
    }
  ],
  "speakers": [
    {
      "name": "The Economic Outlook and Some Comments on My Policy Communication",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "The Economic Outlook and Some Comments on My Policy Communication Watch Live Governor Christopher J. Waller At Reuters NEXT Newsmaker Interview, Washington, D.C.",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/waller20260903a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Unlocking Opportunities for Workers and Entrepreneurs with a Criminal Record",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Unlocking Opportunities for Workers and Entrepreneurs with a Criminal Record Watch Live Governor Michael S. Barr At the Second-Chance Lending Forum, Developing Evidence-Based Policy on Creditworthiness and Criminal History, Washington, D.C.",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/barr20260901a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "In Our Time",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "In Our Time Watch Live Chairman Kevin Warsh At âFinancial Innovation: Implications for Payments and Policy,â an economic policy symposium sponsored by the Federal Reserve Bank of Kansas City, Jackson Hole, Wyoming",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/warsh20260828a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Outlook for the U.S. and Alaskan Economies",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Outlook for the U.S. and Alaskan Economies Governor Lisa D. Cook At the 2026 Economic Luncheon of the Anchorage Economic Development Corporation, Anchorage, Alaska",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/cook20260805a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Navigating Economic Shocks: A Monetary Policymakerâs Perspective",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Navigating Economic Shocks: A Monetary Policymakerâs Perspective Watch Live Vice Chair Philip N. Jefferson At the Stanford Institute for Economic Policy Research, Stanford University, Stanford, California",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/jefferson20260716a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    },
    {
      "name": "Economic Outlook",
      "role": "Federal Reserve speaker",
      "side": "neutral",
      "signal": "NEUTRAL",
      "quote": "Economic Outlook Governor Lisa D. Cook At The Exchequer Club of Washington D.C., Washington, D.C.",
      "impact": "Official Fed speech listing; stance is not automatically inferred.",
      "date": "2026",
      "source": "Federal Reserve",
      "url": "https://www.federalreserve.gov/newsevents/speech/cook20260715a.htm",
      "w": 0.0,
      "s": 0.0,
      "f": 0.0,
      "impactPct": 0.0
    }
  ],
  "levels": {
    "resistance": [
      4320.92,
      4348.05,
      4378.49,
      4637.17
    ],
    "support": [
      4263.35,
      4253.79,
      4232.91,
      4205.78
    ],
    "note": "Classic pivot levels from previous daily OHLC plus recent 20-day extreme; mechanical, not guarantees."
  },
  "calendar": [],
  "pressure": [
    {
      "label": "US 10Y daily move",
      "level": "+1.0 bp",
      "w": 8,
      "dir": "down"
    },
    {
      "label": "Observed XAU momentum",
      "level": "+0.77%",
      "w": 51,
      "dir": "up"
    }
  ],
  "priceSeries": {
    "label": "XAU/USD daily close (Twelve Data)",
    "unit": "USD / troy oz",
    "yMin": 4272.2,
    "yMax": 4495.39,
    "points": [
      {
        "x": "2026-09-03",
        "y": 4473.79
      },
      {
        "x": "2026-09-04",
        "y": 4430.06
      },
      {
        "x": "2026-09-05",
        "y": 4429.03
      },
      {
        "x": "2026-09-06",
        "y": 4429.01
      },
      {
        "x": "2026-09-07",
        "y": 4405.18
      },
      {
        "x": "2026-09-08",
        "y": 4356.03
      },
      {
        "x": "2026-09-09",
        "y": 4401.7
      },
      {
        "x": "2026-09-10",
        "y": 4316.76
      },
      {
        "x": "2026-09-11",
        "y": 4348.87
      },
      {
        "x": "2026-09-12",
        "y": 4348.46
      },
      {
        "x": "2026-09-13",
        "y": 4348.46
      },
      {
        "x": "2026-09-14",
        "y": 4298.35
      },
      {
        "x": "2026-09-15",
        "y": 4293.8
      },
      {
        "x": "2026-09-16",
        "y": 4327.04
      }
    ]
  },
  "macroSeries": {
    "label": "DXY unavailable",
    "unit": "index",
    "yMin": 0,
    "yMax": 1,
    "points": [
      {
        "x": "2026-09-16",
        "y": 0
      }
    ]
  },
  "oddsSeries": {
    "label": "DXY unavailable",
    "unit": "index",
    "yMin": 0,
    "yMax": 1,
    "points": [
      {
        "x": "2026-09-16",
        "y": 0
      }
    ]
  },
  "sources": [
    "Twelve Data — XAU/USD daily market data",
    "Federal Reserve — official speech listings",
    "FRED — DGS10 US 10-Year Treasury Constant Maturity Rate",
    "NewsAPI — recent gold/macro headlines"
  ]
};
